### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by michaelneuder** [celconnell/CompBioLabsAndHomework#1]
my issue is that i am not a collaborator on this project

**Comment by celconnell** [comment]
hello michael neuder, thanks for inquiring, i will see what i can do

**Comment by celconnell** [comment]
the answer is i cannot give you collab privileges on my repo at this point in time because that might be cheating and we both might get expelled. thank you

**Comment by michaelneuder** [comment]
ok that hurts but ok
